version: '3'

services:

  app-node:
    build:
      context: ./node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    container_name: app-node
    entrypoint: wait-for dbmysql:3306 -t 40 -- sh -c "npm install && npm start"
    tty: true
    ports:
      # Settings ports on node is not needed to nginx because nginx connect on node by container's name
      - "3000:3000"
    depends_on:
      - dbmysql
  dbmysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: dbmysql
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    networks:
      - node-network
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - 8080:80
    restart: always
    tty: true
    depends_on:
      - app-node

networks:
  node-network:
    driver: bridge